# Generated by Django 6.0.1 on 2026-01-23 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('AC', 'Active Components'), ('PAS', 'Passive Components'), ('SEMIC', 'Semiconductor Devices'), ('PS', 'Power Supplies'), ('EMECH', 'Electromechanical Components'), ('SENS', 'Sensors'), ('MC', 'Microcontrollers'), ('DLC', 'Digital Logic Components'), ('COMM', 'Communicaton Modules'), ('DISP', 'Display Devices'), ('SWITCH', 'Switches and Protective Devices'), ('CONN', 'Connectors and Interfacing'), ('WIRE', 'Wiring and Cables'), ('PCB', 'PCB and Prototypes'), ('MECH', 'Mechanical Componenets'), ('TOOL', 'Tools and Test Equipment'), ('MISC', 'Miscellaneous')], default='MISC', max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('is_rentable', models.BooleanField(default=True)),
                ('rental_rate', models.IntegerField(default=0)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('datasheet_url', models.URLField(null=True)),
                ('description', models.TextField(default='Component Specifications here')),
                ('location', models.CharField(default='Cupboard', max_length=255)),
            ],
        ),
    ]
