// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

//Project: E-Tan IMS
//Author: Om Kate
//Ver: v1.0

// Enum Definitions
enum user_role {
  admin
  customer
}

enum order_status {
  booked
  accepted
  rejected
  cancelled
  returned
}

// Table Definition
Table user{
  user_id integer [primary key]
  name varchar
  email varchar [not null, unique]
  password_hash varchar [not null]
  pid integer [unique]
  role user_role [not null, default: 'customer']
  phone_number varchar(10) [unique]
  is_member bool [default: false]
}

Table product{
  product_id integer [primary key]
  name varchar [not null]
  quantity integer [not null, default: 0]
  is_rentable bool [not null]
  rental_rate integer [not null, default: 0]
  product_image varchar
  member_rate integer [not null]
  created_at timestamp

}

Table order{
  order_id integer [primary key]
  user_id integer [not null]//FK
  status order_status [not null, default: 'booked']
  created_at timestamp [not null]
  decided_at timestamp
  returned_at timestamp
}

Table order_item{
  order_item_id integer [primary key]
  order_id integer [not null]//FK
  product_id integer [not null]//FK
  quantity integer [not null, default: 1]

  indexes {
    (order_id, product_id) [unique]
  }
}

// Relationships
Ref: order.user_id > user.user_id
Ref: order_item.order_id > order.order_id
Ref: order_item.product_id > product.product_id 
Ref: "user"."user_id" < "user"."email"